# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
print(np.__version__)

1.24.3


#### 3. Create a null vector of size 10 (★☆☆)

In [35]:
arr=np.zeros(10)
arr


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [8]:
x = np.array([3,4,5,6,7,8,77,88,65])
x.size

9

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [36]:
arr=np.zeros(10)
arr[5]=1
arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [37]:
arr=np.arange(10,49)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [50]:
arr=np.array([1,2,3,4])
arr=arr[::-1]
arr

array([4, 3, 2, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [52]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr
# arr=np.arange(9).reshape(3, 3)
# arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [60]:
arr=np.nonzero([1,2,0,0,4,0])
arr
# arr=np.array([1,2,0,0,4,0])
# zer=where(arr==0)
# zer

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [62]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [16]:
arr= np.random.random((3,3,3))
arr

array([[[0.88457095, 0.89090965, 0.02606787],
        [0.61669189, 0.80070693, 0.13237543],
        [0.55020545, 0.70445082, 0.4396471 ]],

       [[0.73832172, 0.13444452, 0.56807558],
        [0.58104168, 0.90648198, 0.06318846],
        [0.88827115, 0.38632607, 0.18693922]],

       [[0.0868746 , 0.63474857, 0.92183822],
        [0.9907823 , 0.39171206, 0.41571766],
        [0.55551864, 0.33771638, 0.886547  ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [70]:
arr=np.random.random((10,10))
max=np.max(arr)
max
min=np.min(arr)
min

0.0043382471349032725

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [72]:
arr=np.random.random(30)
arr1=np.mean(arr)
arr1

0.4469030934858136

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [85]:
arr=np.ones((4,4))
arr[1:3,1:3]=0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [20]:
arr = np.zeros((4,4))
arr[1:-1,1:-1] = 1
print(arr)

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [97]:
arr=np.diag(1+np.arange(5),k=-1)
arr

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [107]:
arr=np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [108]:
arr=np.unravel_index(99,(3,8,9))
arr

(1, 3, 0)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [113]:
arr= np.array([[0,1],[1,0]])
arr1=np.tile(arr,(8,8))
arr1

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [32]:
arr=np.random.random((5,5))
arr1=np.mean(arr)
arr2=np.std(arr)
array=(arr-arr1)/arr2
array

array([[-0.97880508, -0.68512717, -1.52711394,  1.60890387,  1.22012995],
       [ 0.33727442,  0.21948537, -1.117816  ,  1.39367129, -0.72379845],
       [-1.44020452,  0.04331247, -0.93272018, -0.52267563,  0.6967869 ],
       [ 1.4913971 ,  0.32641922, -1.49466547,  0.55293905,  0.5513045 ],
       [ 0.72257604, -0.55421104,  1.76034904, -0.59492956, -0.35248217]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [120]:
arr=np.ones((5,3))
arr1=np.random.random((3,2))
array=np.dot(arr,arr1)
array
# Z = np.dot(np.ones((5,3)), np.ones((3,2)))
# print(Z)

array([[1.31119249, 0.49466825],
       [1.31119249, 0.49466825],
       [1.31119249, 0.49466825],
       [1.31119249, 0.49466825],
       [1.31119249, 0.49466825]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [135]:
arr= np.arange(11)
arr[(3 <arr) & (arr< 8)] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [30]:
#print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [137]:
Z = np.arange(10)
result = 2 << Z >> 2
result

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256], dtype=int32)

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [26]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))

print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-2.14748365e+09]


C:\Users\HP\AppData\Local\Temp\ipykernel_7732\2620438563.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\HP\AppData\Local\Temp\ipykernel_7732\2620438563.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\HP\AppData\Local\Temp\ipykernel_7732\2620438563.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [140]:
# arr=np.array([[1,2,3,4],[2,3,5,6]])
#ar1=np.intersect1d(arr)
arr1=np.array([1,2,3,4])
arr2=np.array([2,3,5,6,7])
arr=np.intersect1d(arr1 , arr2)
arr




array([2, 3])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [60]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\HP\AppData\Local\Temp\ipykernel_13616\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [143]:
yesterday=np.datetime64("today")-np.timedelta64(1)
today=np.datetime64(today)
tommorrow=np.datetime64("today")+np.timedelta64(1)
tommorrow

numpy.datetime64('2023-12-21')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [148]:
arr= np.arange('1998-08', '2023-12', dtype='datetime64[M]')
arr.size

304

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [162]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
b+=a
b*=(-a/2).astype(int)
b

array([  0,  -8, -10, -24])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [180]:
arr=np.random.uniform(0,8,8)
print(arr-arr%1)
print(np.floor(arr))

[0. 0. 0. 4. 7. 4. 6. 7.]
[0. 0. 0. 4. 7. 4. 6. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [192]:
arr=np.zeros((5,5))
arr += np.arange(5)
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [4]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [204]:
# arr=np.linspace(0,1,11)[:-1]
# arr
vector = np.linspace(0, 1, 12)[1:-1]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [11]:
arr= np.random.randint(15,size=(10))
arr.sort()
arr

array([ 3,  3,  5,  6,  9, 10, 11, 12, 14, 14])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [8]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [51]:
a=np.random.randint((1,4,7))
# b=np.random.randint(0,3,7)
# c= np.allclose(a,b)
# c
a

array([0, 1, 6])

#### 43. Make an array immutable (read-only) (★★☆)

In [40]:
arr= np.zeros(10)
arr.flags.writeable = False
#arr[0]= 1
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [41]:
arr= np.random.random((10,2))
a=arr[:,0]
b=arr[:,1]
R = np.sqrt(arr**2+arr**2)
T = np.arctan2(b,a)
print(R)
print(T)

[[1.35566355 0.32187901]
 [0.19487627 1.03480886]
 [0.94483678 0.38632826]
 [0.76203059 0.13710767]
 [0.10210758 0.23601275]
 [1.10538924 0.86569863]
 [0.27787133 0.78161888]
 [0.69135646 0.24291993]
 [0.53090296 0.86030492]
 [0.7131152  1.10930329]]
[0.2331162  1.38465535 0.38814111 0.17801943 1.16247584 0.66438909
 1.22922354 0.33789223 1.01789069 0.99946417]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [42]:
arr= np.random.random(10)
arr[arr.argmax()] = 0
arr

array([0.29452751, 0.80987905, 0.39921264, 0.67815682, 0.61656057,
       0.        , 0.27405099, 0.39499383, 0.91557809, 0.90320312])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [43]:
arr= np.zeros((5,5), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [44]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [46]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((4,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)