### Questions 1

Create a matrix of 5x5 with random integers, after that swap its first and last rows.

In [142]:
import numpy as np

arr= np.random.random((5,5)).reshape(5,5)
print(arr)
arr[[0,4]] =arr[[4,0]]
print(arr)

[[0.66980068 0.312425   0.69219813 0.82857584 0.53329125]
 [0.73466193 0.57689013 0.5394772  0.69477222 0.43336103]
 [0.03054836 0.48213936 0.82142507 0.40804675 0.84242582]
 [0.77221402 0.97112573 0.21732685 0.32721384 0.45539054]
 [0.5872719  0.98025128 0.23697491 0.99483147 0.12442137]]
[[0.5872719  0.98025128 0.23697491 0.99483147 0.12442137]
 [0.73466193 0.57689013 0.5394772  0.69477222 0.43336103]
 [0.03054836 0.48213936 0.82142507 0.40804675 0.84242582]
 [0.77221402 0.97112573 0.21732685 0.32721384 0.45539054]
 [0.66980068 0.312425   0.69219813 0.82857584 0.53329125]]


### Question 2

Create a 2D array, remove all rows that contain at least one zero.

In [159]:
arr=np.arange(5,5)
arr

array([], dtype=int32)

### Question 3

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

### Question 4

Write a NumPy program to remove the duplicate elements of an array.<br>
Original array:
[10 10 20 20 30 30]


In [74]:
arr= np.array([10,10,20,20,30,30])
print(arr)
new = np.unique(arr)
print(new)

[10 10 20 20 30 30]
[10 20 30]


### Question 5

Write a NumPy program to create a 3x3x3 array with random values.

In [5]:
arr= np.random.random((3,3,3))
arr

array([[[0.31189134, 0.68987644, 0.60256128],
        [0.09834188, 0.41628534, 0.71944889],
        [0.04367458, 0.54349973, 0.20079236]],

       [[0.7497405 , 0.69499894, 0.48058266],
        [0.91013485, 0.37487202, 0.56406838],
        [0.93695788, 0.69642329, 0.28428058]],

       [[0.51874438, 0.04323697, 0.21705609],
        [0.89015988, 0.08974214, 0.22897987],
        [0.36254491, 0.20657251, 0.69740323]]])

### Question 6

Write a NumPy program to create a random vector of size 10 and sort it.
<b>Note:<\b> Do not use builtin sorting function

In [152]:
import numpy as np
arr1=np.random.randint(15,size=(10))
print(arr1)
for i in range(0,len(arr1)):
    for j in range(0,len(arr1)):
        if arr1[i]<arr1[j]:
            temp=arr1[j]
            arr1[j]=arr1[i]
            arr1[i]=temp
print(arr1)

[ 7 11 11 12  0 12  0 11  7 12]
[ 0  0  7  7 11 11 11 12 12 12]


### Question 7

Write a NumPy program to check two random arrays are equal or not.

In [71]:
arr1= np.random.randint(1,10,5)
print(arr1)
arr2= np.random.randint(1,10,5)
print(arr2)
if arr1  

[5 3 8 9 6]
[9 6 3 5 4]
False


### Question 8 

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.<br>

Original array:<br>
[[10 40]<br>
[30 20]]

### Question 9

Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.<br>

Original array:<br>
[-1.6 -1.5 -0.3 0.1 1.4 1.8 2. ]

In [25]:
arr=np.array([-1.6,-1.5,-0.3,0.1,1.4,1.8,2.])
arr
print(np.floor(arr))
print(np.ceil(arr))
#print(np.truncated(arr))

[-2. -2. -1.  0.  1.  1.  2.]
[-1. -1. -0.  1.  2.  2.  2.]


### Questions 10

Write a NumPy program to display all the dates for the month of March, 2017

In [83]:
arr= np.arange('2017-03-01', '2023-12-21', dtype='datetime64[M]')
arr

array(['2017-03', '2017-04', '2017-05', '2017-06', '2017-07', '2017-08',
       '2017-09', '2017-10', '2017-11', '2017-12', '2018-01', '2018-02',
       '2018-03', '2018-04', '2018-05', '2018-06', '2018-07', '2018-08',
       '2018-09', '2018-10', '2018-11', '2018-12', '2019-01', '2019-02',
       '2019-03', '2019-04', '2019-05', '2019-06', '2019-07', '2019-08',
       '2019-09', '2019-10', '2019-11', '2019-12', '2020-01', '2020-02',
       '2020-03', '2020-04', '2020-05', '2020-06', '2020-07', '2020-08',
       '2020-09', '2020-10', '2020-11', '2020-12', '2021-01', '2021-02',
       '2021-03', '2021-04', '2021-05', '2021-06', '2021-07', '2021-08',
       '2021-09', '2021-10', '2021-11', '2021-12', '2022-01', '2022-02',
       '2022-03', '2022-04', '2022-05', '2022-06', '2022-07', '2022-08',
       '2022-09', '2022-10', '2022-11', '2022-12', '2023-01', '2023-02',
       '2023-03', '2023-04', '2023-05', '2023-06', '2023-07', '2023-08',
       '2023-09', '2023-10', '2023-11'], dtype='dat

### Question 11

Write a NumPy program to create 24 python datetime.datetime objects (single object for every hour), and then put it in a numpy array.

In [126]:
arr=datetime.datetime(2023, 1, 1)
dt_array = np.array([arr + datetime.timedelta(hours=i)for i in range(24) ])
print(dt_array) 

[datetime.datetime(2023, 1, 1, 0, 0) datetime.datetime(2023, 1, 1, 1, 0)
 datetime.datetime(2023, 1, 1, 2, 0) datetime.datetime(2023, 1, 1, 3, 0)
 datetime.datetime(2023, 1, 1, 4, 0) datetime.datetime(2023, 1, 1, 5, 0)
 datetime.datetime(2023, 1, 1, 6, 0) datetime.datetime(2023, 1, 1, 7, 0)
 datetime.datetime(2023, 1, 1, 8, 0) datetime.datetime(2023, 1, 1, 9, 0)
 datetime.datetime(2023, 1, 1, 10, 0) datetime.datetime(2023, 1, 1, 11, 0)
 datetime.datetime(2023, 1, 1, 12, 0) datetime.datetime(2023, 1, 1, 13, 0)
 datetime.datetime(2023, 1, 1, 14, 0) datetime.datetime(2023, 1, 1, 15, 0)
 datetime.datetime(2023, 1, 1, 16, 0) datetime.datetime(2023, 1, 1, 17, 0)
 datetime.datetime(2023, 1, 1, 18, 0) datetime.datetime(2023, 1, 1, 19, 0)
 datetime.datetime(2023, 1, 1, 20, 0) datetime.datetime(2023, 1, 1, 21, 0)
 datetime.datetime(2023, 1, 1, 22, 0) datetime.datetime(2023, 1, 1, 23, 0)]


### Question 12

Write a NumPy program to concatenate element-wise two arrays of string.<br>
<b>Example <\b>
Array1:<br>
['Python' 'PHP']<br>
Array2:<br>
[' Java' ' C++']<br>
new array:<br>
['Python Java' 'PHP C++']<br>